const sendMail=require("./sendEmail")
function sendEmailOTP(obj){
    let subject="OTP-RatingApp";
    let template=`
        <p> Hi <strong>$$EMPLOYEENAME$$</strong> <br>
            <br>
            Please find the following OTP <strong>$$OTP$$</strong>, to update password for Rating Application.it is auto
            generated by system and Please do not share with anyone.


            <br>
            <br>
            <br>
            Thanks & Regards, </br>
            <strong>Signiwis Technologies.
            </strong> </br>
            <a href="https://www.signiwis.com/">www.signiwis.com</a>
        </p>
        `
        template=template.replace('$$EMPLOYEENAME$$',obj.EMPLOYEENAME);
        template=template.replace('$$OTP$$',obj.Otp); 
        console.log()
    sendMail(obj.Email,subject, template);
}

module.exports=sendEmailOTP

